apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: nimbleway@ma.il
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: nimbleway-letsencrypt-secret-prod
    solvers:
    - http01:
        ingress:
          class: nginx
