name: 'Deploy App'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  kubeconfig_job:
    name: 'kubeconfig_job'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./Terraform
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Refresh outputs and get data
    - name: Terraform Refresh
      env:
        TF_VAR_do_token: ${{ secrets.TF_API_TOKEN }}
      run: terraform refresh

    - name: Terraform Output
      run: terraform output -json kubernetes-cluster-prod-1-output | jq -r .raw_config > kubeconfig

    - uses: actions/upload-artifact@master
      with:
        name: kubeconfig_file
        path: ./kubeconfig

  deploy_app:
    name: "deploy_app"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./Resources
        shell: bash
